Creating Enumerables method
jairjy/Microverse-202-Advanced-Building-Blocks-Enumerables pull request #1
Opened 2019-10-18 07:09 UTC by jairjy

2019-10-21 18:59 UTC, samgaco requested changes
Hi @jairjy :high_brightness: 

I left you some comments below about what functionalities your methods are lacking. Please contrast your methods against the original ones [here](https://ruby-doc.org/core-2.6.3/Enumerable.html).

If you would need further clarification with some concrete examples you may **ask me in the comments** below or slack, my name is _Samuel García_ over there.

* Don't forget to solve the conflicts in your branch as well.

This project is a bit tricky but it will help you with getting to know ruby better, so you will be feeling more fluent moving on, therefore good spirit :muscle: 

-------------------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +      yield to_a[counter]
- [ ] my_each returns an Enumerator if no block is given
- [ ] my_each_with_index returns an enumerator if no block is given

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +    while i < to_a.length
- [ ] my_select returns an enumerator if no block is given

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +    elsif !pattern == true
- [ ] my_all? returns true if the block never returns false or nil
- [ ] my_all? when no block or argument is given returns true when none of the collection members are false or nil
- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +    elsif !pattern == true
- [ ] my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +    elsif !pattern == true
- [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] my_none? when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +      my_each { |item| count += 1 if yield item }
- [ ] my_count returns the number of items in enum through enumeration
- [ ] my_count counts the number of items in enum that are equal to item if an argument is given

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +    to_a.my_each do |item|
- [ ] my_map returns an Enumerator if no block is given

2019-10-21 18:59 UTC, samgaco commented on enum.rb
> +
- [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-10-24 15:44 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: . However, some methods still don't meet with the requirements. Check the code comments below for the requirements :arrow_down: 

- **[REQUIRED]** fix the merging conflict that you have in this branch

### That's it :relaxed: . When finished, kindly resubmit another code review request :pray: 

_happy coding_ :v: 
**Ahmed Mahfoudh**

2019-10-24 15:44 UTC, stratospherique commented on enum.rb
> +  end
* [ ] my_all? when no block or argument is given returns true when none of the collection members are false or nil

2019-10-24 15:44 UTC, stratospherique commented on enum.rb
> +  end
* [ ] my_any? when no block or argument is given returns true if at least one of the collection is not false or nil

2019-10-24 15:44 UTC, stratospherique commented on enum.rb
> +  end
* [ ] my_none? when no block or argument is given returns true only if none of the collection members is true

2019-10-24 15:44 UTC, stratospherique commented on enum.rb
> +  end
* [ ] my_count returns the number of items in enum through enumeration

2019-10-25 02:27 UTC, uche-inyama requested changes
## Hi jairjy

Everything looks good with your enumerable module. :100: 

However, you have a  conflict to resolve: 

```
      This branch has conflicts that must be resolved
       Conflicting files
       .rubocop.yml
 ```
You will find this information :point_up_2: at the buttom of this pull request.


 **After resolving the conflict, submit another form for a code review**

#### ``` Have a great day ``` :slightly_smiling_face: 

@ Uchechukwu Henry Inyama

2019-10-25 21:15 UTC, uche-inyama approved these changes
## Hi jairjy!

Everything is good now, go ahead and merge. :clap: 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2019-10-25 21:16 UTC, merged